### ISSUE TITLE
Timesformer 

### ISSUE THREAD

**Issue by Steven-jiaqi** [vandal-vpr/vg-transformers#12]
With your help, I have successfully run the cct+seqvlad experiment. But when I was running the Timesformer experiment, I found some errors:
AttributeError: ‘Namespace' object has no attribute 'features_dim'
It happens in "vg-transformers/tgv/models/tgv_net.py" line 43
self.meta = {'outputdim': args.features_dim}
And i can not find the 'args.features_dim' variant in the code project.
Should I assign a value to this parameter in the parser.py?
Thanks for your reply!

**Comment by ga1i13o** [comment]
Hello, I was not able to reproduce your issue.
The `args.features_dim` value is assigned in the function below:

https://github.com/vandal-vpr/vg-transformers/blob/25537ed1689d4b5401113f6c4476fb8f0cf28158/tvg/models/tvg_net.py#L159

 Specifically at this line for the TimeSformer
https://github.com/vandal-vpr/vg-transformers/blob/25537ed1689d4b5401113f6c4476fb8f0cf28158/tvg/models/tvg_net.py#L179

Have you pulled the last version of the code?

**Comment by ga1i13o** [comment]
Solved in https://github.com/vandal-vpr/vg-transformers/issues/13
