### ISSUE TITLE
can you tell me the hyperparameter settings used in your comparative experiments in your paper?

### ISSUE THREAD

**Issue by dominicekmasd** [vandal-vpr/vg-transformers#19]
![图片](https://user-images.githubusercontent.com/130672469/234602047-9a99c645-1f6c-45e9-a089-5091abc40c22.png)

Can you tell me what is the value of seq_length in this table? and if the backbone used is resnet, at which layer were they truncated? for example, if resnet50 was used, were they truncated at r50l3 or r50l4?

![图片](https://user-images.githubusercontent.com/130672469/234602839-06444ecd-83cb-435f-9c00-c3e059168863.png)

and how about the settings of this chart?

**Comment by ga1i13o** [comment]
Hello, the sequence length, unless differently specified (e.g. in the robustness to sequence length table) is always 5.
The resnets were truncated at l3

In Tab III, we reversed the order of the frames in the database sequences, and performed inference 
with the models trained in the standard setting

**Comment by dominicekmasd** [comment]
Think you for your help !

**Comment by dominicekmasd** [comment]
Think you for your help !
