### ISSUE TITLE
Is there a problem with the representation of L in Formula 1 of your paper?

### ISSUE THREAD

**Issue by wpumain** [vandal-vpr/vg-transformers#20]
Is there a problem with the representation of L in Formula 1 of your paper? In the paper, L represents the sequence length. Should L in Formula 2 be changed to represent the number of clusters in the NetVLAD algorithm?
![图片](https://user-images.githubusercontent.com/122344271/235598878-de279bf1-87dc-43da-8591-7e10239048bd.png)
![图片](https://user-images.githubusercontent.com/122344271/235598948-b104ae12-40b4-4957-9e18-22f699ecefe8.png)

**Comment by ga1i13o** [comment]
in that formula, the netvlad cluster index is $k$. Therefor for each cluster in this formula we compute the assignment, on all descriptors ($M$ is the number of descriptors in an image), for all frames in the sequence; with $L$ sequence length

**Comment by dominicekmasd** [comment]
Think you for your help!

**Comment by wpumain** [comment]
Think you for your help!
