### ISSUE TITLE
the Oxford dataset

### ISSUE THREAD

**Issue by Steven-jiaqi** [vandal-vpr/vg-transformers#22]
Thanks a lot for your great work. When I download the Oxford dataset, the format of the images is always grayscale instead of color, have you encountered this? If so how can I fix it, sorry to bother you!

**Comment by ga1i13o** [comment]
yes, that's the original format for oxford. we provide scripts for pre processing
alternatively, in the README of the repo you find links to download from GDrive the already processed version
