### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by quocanh010** [vandal-vpr/vg-transformers#23]
Can you pls post a LICENSE statement? Thanks

**Comment by ga1i13o** [comment]
done, thanks for the tip

**Comment by quocanh010** [comment]
Thanks for the quick response!! Could you pls add an example on how to run robotcar dataset for training. Thanks a bunch!

**Comment by ga1i13o** [comment]
Done. You simply need to change the dataset path, we did not modify any other training hyperparameter.
For downloading the dataset, I suggest you use the version we released via GDrive (see Readme)
The alternative is to download from official website and use our scripts to format it, but it takes some time and I have not properly cleaned that code yet so may have some issues with paths
