### ISSUE TITLE
Confusion about table II in paper

### ISSUE THREAD

**Issue by kaiyi98** [vandal-vpr/vg-transformers#3]
Thanks for your work.
For table II in paper, Intermediate Fusion, how to achieve fusion using the SeqNet? I guess that firstly using backbone (vgg-16/resnet-18/resnet-50/cct224/cct384) to get global descriptor, and then using the conv1D in original seqnet paper to fusion sequential descriptors. Is that so?

If so, a Linear() layer should been followed cct224/384 to generate 4096 dim global descriptor, and vgg-16/resnet-18/resnet-50 should flatten feature maps and Linear() to 4096 dim global descriptor, Is that so?

If so, the seqnet in your paper is just the network structure, and It doesn't make sense that comparing your results with original seqnet paper, Is that so?

**Comment by ga1i13o** [comment]
Hello, for SeqNet comparison we did the following:
the SeqNet paper uses pre-computed single-frame NetVLAD descriptors, reduced to 4096-d via PCA, which are kept fixed.
To compare other backbones we did the same, trained for each backbone NetVLAD on single frames, then computed the PCA and saved the descriptors. Then we used the official SeqNet repo, which has the conv1d pooling.
