### ISSUE TITLE
Can the 6G GPU memory run the program?

### ISSUE THREAD

**Issue by wpumain** [vandal-vpr/vg-transformers#7]
RTX3060  6G  can the 6G GPU memory run the program?

**Comment by ga1i13o** [comment]
Hello, if you want to use sequence length of 5 as in our paper, you should be able to do so with a bit of caution
1. use lightweight backbones -> resnet-18 or cct-224. You should then be able to use seqvlad
2.  if the above is not enough you can lower the train_batch_size to 2. I've found it to not affect significantly results

This should do the trick and fit into 6 Gbs;  however if you want to further reduce GPU memory occupancy you can reduce the number of negative samples for the triplet ( 5 by default, `nNeg` in the parser) to  2  or 3.

hope this helps

**Comment by wpumain** [comment]
Think you  for your help
